### ISSUE TITLE
Wrong image size displayed after resizing the window to a larger size

### ISSUE THREAD

**Issue by Tetane** [Sirtsu55/VulraySamples#6] opened 2023-10-16 09:44 UTC
### System information
Windows 10, RTX 3090

### Issue description
When resizing the window to a larger size, the image seems to be scaled even larger than it is supposed to be.
Before resizing:
![Capture d’écran 2023-10-16 113404](https://github.com/Sirtsu55/VulraySamples/assets/13542748/84439873-4777-42eb-9629-c6e9d47b7ecf)
After resizing:
![Capture d’écran 2023-10-16 113429](https://github.com/Sirtsu55/VulraySamples/assets/13542748/d39bb2c7-4259-4406-bb61-426429b17319)

We can see that the image is pixelated like it was resize bigger than it's actual size before being displayed.

### Steps to reproduce
Launch HelloTriangle (or any other sample) and resize it to a larger size than its initial size.

**Comment by Sirtsu55** [comment] 2023-10-16 10:48
The pixelating is expected behaviour and can be changed from 
[here](https://github.com/Sirtsu55/VulraySamples/blob/5d4bb0d54138a5f2661e3fa5f81e4a2acdb12224/Samples/HelloTriangle/HelloTriangle.cpp#L332) by replacing the filter to `vk::Filter::eLlinear`. For other samples its abstracted away [here](https://github.com/Sirtsu55/VulraySamples/blob/5d4bb0d54138a5f2661e3fa5f81e4a2acdb12224/Base/Application.cpp#L346) and do the same thing as above for this line also.

The triangle shifting effect is mainly due to the camera readjusting and you can move around the scene with WASD keys and rotate using your mouse, so it shouldn't be much of a problem :)

**Comment by Tetane** [comment] 2023-10-16 11:27
I really don't think this should be an expected behavior. 
If the window size is passed to the ray dispatch function, and the image buffer is resized to the window size, the image displayed should remain pixel perfect (one pixel of the image equal to one pixel of the screen). But this is not the case.

**Comment by Sirtsu55** [comment] 2023-10-16 11:43
You're right, the dispatch function should trace the rays according to render resolution and not the window resolution.

But I'll give a rundown on what is/should happening::
- There is a fixed output image that the raytraced image is rendered to when instantiating the Application class, which is the size 1280x720, in `Application.h`.
- There are member variables tracking the render resolution and the window resolution. If the resize resolution is greater than the allocated texture, it will keep the render resolution to the size of the output image and change the window resolution variables. Only the swapchain buffer resolution changes, not the output buffer.
- It will trace rays by the render resolution (needs to be fixed) and draw the output image on top of the swapchain image which is pixel perfect if window size is less or equal to the output texture. Otherwise it will upscale to fit.

If you have a fix for it I would be happy to accept a PR. Nice find!

**Comment by Tetane** [comment] 2023-10-16 13:52
I don't have a clear solution right now but I think I see something that might be part of the issue.
In the `Application::HandleResize()` function, you destroy the swapchain's ImageViews but not the Images and the swapchain itself, then you rebuild them with the exact same parameters from `mOldSwapchain`.

Last time I've built a Vulkan program, during the resize I destroyed the swapchain along with the images and imageViews, and rebuilt it with the new extent corresponding to the new window size.

Also, in the examples from Sascha Willems he seems to be handling the resize and the command buffer a bit differently than you: https://github.com/SaschaWillems/Vulkan/blob/master/examples/raytracingbasic/raytracingbasic.cpp#L703

**Comment by Sirtsu55** [comment] 2023-10-16 14:25
The problem is [this line](https://github.com/Sirtsu55/VulraySamples/blob/5d4bb0d54138a5f2661e3fa5f81e4a2acdb12224/Samples/HelloTriangle/HelloTriangle.cpp#L307C94-L308C1). Replacing it with `VRDev->DispatchRays(mRTPipeline, mSBTBuffer, mRenderWidth, mRenderHeight, 1, renderCmd);` seems to solve the problem

**Comment by Tetane** [comment] 2023-10-16 14:42
Ok, yes, it solves the issue if you want to keep the current behavior of the swapchain and the image buffer not being resized to the new window size.

**Comment by Sirtsu55** [comment] 2023-10-16 14:45
Yeah. As I said before if you've implemented a better resize functionality, please make a PR 😄. I'll close this after I commit the changes.

**Comment by Tetane** [comment] 2023-10-16 14:50
One more thing little thing. In the HelloTriangle.cpp you copied the content of Application::BlitImage() instead of just calling it. You may want to change that. https://github.com/Sirtsu55/VulraySamples/blob/master/Samples/HelloTriangle/HelloTriangle.cpp#L310

**Comment by Sirtsu55** [comment] 2023-10-16 14:53
That was intentional. I dont want to abstract away an important part from the introductory sample. The later ones have it abstracted, because it is redundant.

**Comment by Sirtsu55** [comment] 2023-10-24 05:44
Commit 4a0b2881943d2b1ef2663fdabfa54c7a40cd8165 fixes this issue.

**Closed as completed by Sirtsu55** 2023-10-24 05:44 UTC
